- name: Uninstall java-1.7.0 by yum
  yum:
    name: java-1.7.0
    state: absent

- name: Install java-1.8.0 by yum
  yum:
    name: java-1.8.0-openjdk-headless
    state: latest

- name: Create minecraft directory
  file:
    path: /minecraft
    state: directory

- name: Download minecraft server
  get_url:
    url: https://launcher.mojang.com/v1/objects/d0d0fe2b1dc6ab4c65554cb734270872b72dadd6/server.jar
    dest: /minecraft

- name: Changing permissions of server.jar
  file:
    path: /minecraft/server.jar
    mode: '0755'
